ASSEMBLIES: 
  - "AGS2000a2.ragtag.scaffold"
  - "AGS2000a5.ragtag.scaffold"
  - "AGS2000.MW.scaffold"
  - "Hilliard.MW.scaffold"
  - "Triticum_aestivum_AGS2000"
  - "Triticum_aestivum_Hilliard"

VECSCREEN_DB: "resources/dbs/UniVec"

VRN_DB: "resources/dbs/TripleDirkC_vrn_genes.fa"

PPD_DB: "resources/dbs/Taes_Ppd_genes.fa"
