ASSEMBLIES: 
  - "Taes_Hilliard_1.2"
  - "Taes_AGS2000_1.1"
  - "IL0218228.ragtag.scaffold"
  - "LA03136E71.ragtag.scaffold"
  - "MO080104.ragtag.scaffold"
  - "Jagger.ragtag.scaffold"

VECSCREEN_DB: "resources/dbs/UniVec"

VRN1_DB: "resources/dbs/TripleDirkC_vrn_genes.fa"

VRN2_DB: "resources/dbs/Taes_VRN2.fa"

VRN3_DB: "resources/dbs/Taes_VRN3.fa"

RHT8_DB: "resources/dbs/Taes_Rht8.fa"

PPD_DB: "resources/dbs/Taes_Ppd_genes.fa"

