ASSEMBLIES: 
  - "AGS2000a2.ragtag.scaffold"
  - "AGS2000a5.ragtag.scaffold"
  - "AGS2000.MW.scaffold"
  - "Hilliard.MW.scaffold"
  - "Triticum_aestivum_AGS2000"
  - "Triticum_aestivum_Hilliard"
  - "Triticum_aestivum_jagger.PGSBv2.1.dna.toplevel"
  - "Attraktion.rename"
  - "Triticum_aestivum_Hilliard_NCBI_Dec2023"
  - "Triticum_aestivum_AGS2000_NCBI_Dec2023"

VECSCREEN_DB: "resources/dbs/UniVec"

VRN1_DB: "resources/dbs/TripleDirkC_vrn_genes.fa"

VRN2_DB: "resources/dbs/Taes_VRN2.fa"

RHT8_DB: "resources/dbs/Taes_Rht8.fa"

PPD_DB: "resources/dbs/Taes_Ppd_genes.fa"
